version: '3'

services:
  database:
    container_name: postgresql
    build:
      context: ./distribution/images/postgresql
    environment:
      POSTGRES_DB: alexandrie
      POSTGRES_USER: alexandrie
      POSTGRES_PASSWORD: additi
    volumes:
      - $HOME/PhpstormProjects/Symfony-Alexandrie/db-data/:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  php:
    container_name: php
    build:
      context: ./distribution/images/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/symfony_docker
    depends_on:
      - database

  web_server:
    container_name: nginx
    build:
      context: ./distribution/images/nginx
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/symfony_docker
      - ./distribution/images/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
